// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrCVdXwWbaAntMyMi2Wbn1gJ5lkWH1d24',
    appId: '1:1032303212122:web:676ba8f2a09165147a0a63',
    messagingSenderId: '1032303212122',
    projectId: 'task-tracker-123',
    authDomain: 'task-tracker-123.firebaseapp.com',
    storageBucket: 'task-tracker-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflxZ474t7Adh8uMqTOcOmp_cIOiRgnCI',
    appId: '1:1032303212122:android:0ae54c9c9b35b05f7a0a63',
    messagingSenderId: '1032303212122',
    projectId: 'task-tracker-123',
    storageBucket: 'task-tracker-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCo8RXgU1sFmuape8VLEYkFZPmgGvEGE',
    appId: '1:1032303212122:ios:57b723fd64ac48847a0a63',
    messagingSenderId: '1032303212122',
    projectId: 'task-tracker-123',
    storageBucket: 'task-tracker-123.firebasestorage.app',
    iosBundleId: 'com.example.taskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCo8RXgU1sFmuape8VLEYkFZPmgGvEGE',
    appId: '1:1032303212122:ios:57b723fd64ac48847a0a63',
    messagingSenderId: '1032303212122',
    projectId: 'task-tracker-123',
    storageBucket: 'task-tracker-123.firebasestorage.app',
    iosBundleId: 'com.example.taskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrCVdXwWbaAntMyMi2Wbn1gJ5lkWH1d24',
    appId: '1:1032303212122:web:68677d27d02fa6f57a0a63',
    messagingSenderId: '1032303212122',
    projectId: 'task-tracker-123',
    authDomain: 'task-tracker-123.firebaseapp.com',
    storageBucket: 'task-tracker-123.firebasestorage.app',
  );
}
